version: '3.5'

services:
  frontend-example:
    image: frontend-example
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
    networks:
      - frontend
    container_name: frontend-example
  backend-example:
    image: backend-example
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
    volumes:
      - ./logs.txt:/app/logs.txt
    ports:
      - 8000:8000
    networks:
      - backend
    container_name: backend-example
  redis:
    image: redis:6.0
    networks:
      - backend
    container_name: redis

networks:
  backend:
    name: backend
  frontend:
    name: frontend
