FROM node:10-alpine AS builder

COPY . /app/

WORKDIR /app

# Install node
RUN npm install && \
    API_URL=http://localhost:80/api npm run build

# Copy app to container and start server

FROM node:10-alpine
COPY --from=builder /app/dist /dist
RUN npm install -g serve && \
    adduser -D app && \
    /bin/chown -R app:app /dist
USER app
EXPOSE 5000
CMD ["serve", "-s", "-l", "5000", "dist"]
