version: '3.5'

services:

  frontend-example:
    image: frontend-example
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
    networks:
      - frontend
    container_name: frontend-example

  backend-example:
    image: backend-example
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=asdf1234
    volumes:
      - ./logs.txt:/app/logs.txt
    ports:
      - 8000:8000
    networks:
      - backend
    container_name: backend-example
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.0
    networks:
      - backend
    container_name: redis

  db:
    image: postgres:13
    restart: unless-stopped
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=asdf1234
    container_name: db


networks:
  backend:
    name: backend
  frontend:
    name: frontend
